import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./stores/**/*.{ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // Luminous Warmth design system
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#524434",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#857462",
        "outline-variant": "#d7c3ae",
        "surface-tint": "#835400",
        "primary-container": "#f9a826",
        "on-primary-container": "#674100",
        "inverse-primary": "#ffb957",
        "on-primary": "#ffffff",
        "secondary-container": "#fec7c7",
        "on-secondary-container": "#7a5051",
        "on-secondary": "#ffffff",
        tertiary: "#585f66",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b3bac2",
        "on-tertiary-container": "#434a51",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffddb5",
        "primary-fixed-dim": "#ffb957",
        "on-primary-fixed": "#2a1800",
        "on-primary-fixed-variant": "#643f00",
        "secondary-fixed": "#ffdad9",
        "secondary-fixed-dim": "#efb9b9",
        "on-secondary-fixed": "#301214",
        "on-secondary-fixed-variant": "#633c3d",
        "tertiary-fixed": "#dce3eb",
        "tertiary-fixed-dim": "#c0c7cf",
        "on-tertiary-fixed": "#151c22",
        "on-tertiary-fixed-variant": "#40484e",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      boxShadow: {
        glass: "0 24px 70px rgba(131, 84, 0, 0.08)",
        glow: "0 16px 34px rgba(249, 168, 38, 0.22)"
      }
    }
  },
  plugins: []
}

export default config
