"""create_core_tables

Revision ID: 6caea9718aa3
Revises: 
Create Date: 2026-05-22 09:09:54.767563+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '6caea9718aa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('scene', sa.String(length=128), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('parameters_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_by', sa.String(length=32), server_default=sa.text("'system'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'scene', 'version_no', name='uq_prompt_versions_agent_scene_version')
    )
    op.create_index('idx_prompt_versions_agent_scene', 'prompt_versions', ['agent_name', 'scene'], unique=False)
    op.create_index('idx_prompt_versions_status', 'prompt_versions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'student'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=32), server_default=sa.text("'private'"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_owner_id', 'courses', ['owner_id'], unique=False)
    op.create_index('idx_courses_status', 'courses', ['status'], unique=False)
    op.create_index('idx_courses_visibility', 'courses', ['visibility'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('profile_summary', sa.Text(), nullable=True),
    sa.Column('mastery_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('weak_points', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('strategy_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_student_profiles_user_id', 'student_profiles', ['user_id'], unique=False)
    op.create_table('learning_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('answer_length', sa.String(length=32), nullable=True),
    sa.Column('explanation_style', sa.String(length=64), nullable=True),
    sa.Column('resource_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('prompt_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.8000'), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_preferences_user_course', 'learning_preferences', ['user_id', 'course_id'], unique=False)
    op.create_index('idx_learning_preferences_version', 'learning_preferences', ['version_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_learning_preferences_version', table_name='learning_preferences')
    op.drop_index('idx_learning_preferences_user_course', table_name='learning_preferences')
    op.drop_table('learning_preferences')
    op.drop_index('idx_student_profiles_user_id', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('idx_courses_visibility', table_name='courses')
    op.drop_index('idx_courses_status', table_name='courses')
    op.drop_index('idx_courses_owner_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_prompt_versions_status', table_name='prompt_versions')
    op.drop_index('idx_prompt_versions_agent_scene', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
